language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm]

env:
  - SYMFONY_VERSION=2.5.*

matrix:
  fast_finish: true
  include:
  - {php: 5.3.3, env: "SYMFONY_VERSION=2.3.*"}
  - {php: 5.5, env: "SYMFONY_VERSION=2.4.*"}
  allow_failures:
  - {php: hhvm}

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle=$SYMFONY_VERSION; fi;'
  - sh -c 'if [  $(phpenv version-name) = "5.3.3" ]; then composer remove --no-update --dev -n fabpot/php-cs-fixer; fi;'
  - composer install --dev
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
  - $HOME/.composer/
